sonar.projectKey=ben-ranford_wtgc
sonar.projectName=wtgc
sonar.sourceEncoding=UTF-8
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/testdata/**,**/vendor/**
sonar.go.coverage.reportPaths=.artifacts/coverage.out
